" Generated by vim-plug
" Sat Jun 22 13:11:39 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['applescript.vim'].commit = '00840b4059c7884120913907f4778092edb006f7'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = 'd250c63aa13ead745e3a40f61fdd3470efde3923'
silent! let g:plugs['cmp-nvim-lsp'].commit = '39e2eda76828d88b773cc27a3f61d2ad782c922d'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['editorconfig-vim'].commit = 'e014708e917b457e8f6c57f357d55dd3826880d4'
silent! let g:plugs['fzf'].commit = 'c4a9ccd6afc3698a57a6b938ebba6d85238033e2'
silent! let g:plugs['fzf.vim'].commit = '279e1ec068f526e985ee7e3f62a71f083bbe0196'
silent! let g:plugs['indent-blankline.nvim'].commit = 'd98f537c3492e87b6dc6c2e3f66ac517528f406f'
silent! let g:plugs['mason-lspconfig.nvim'].commit = '9ae570e206360e47d30b4c35a4550c165f4ea7b7'
silent! let g:plugs['mason-tool-installer.nvim'].commit = 'c5e07b8ff54187716334d585db34282e46fa2932'
silent! let g:plugs['mason.nvim'].commit = 'c43eeb5614a09dc17c03a7fb49de2e05de203924'
silent! let g:plugs['neoformat'].commit = '82864d6c7926c4f3b535a2fd7eab919b116fc969'
silent! let g:plugs['nvim-cmp'].commit = 'a110e12d0b58eefcf5b771f533fc2cf3050680ac'
silent! let g:plugs['nvim-lspconfig'].commit = '3c8346db23033fa49ce0eef2e89dbe91cfd54f21'
silent! let g:plugs['nvim-tree.lua'].commit = '2086e564c4d23fea714e8a6d63b881e551af2f41'
" Leaving uncommented since we want latest updates
" silent! let g:plugs['nvim-treesitter'].commit = '122b4d3db1616c1f1305b847c5ed2217c4c329f1'
silent! let g:plugs['nvim-web-devicons'].commit = 'c0cfc1738361b5da1cd0a962dd6f774cc444f856'
silent! let g:plugs['papercolor-theme'].commit = '0cfe64ffb24c21a6101b5f994ca342a74c977aef'
silent! let g:plugs['vim-argumentative'].commit = '63a5f7deb675c38126de626f4c00e000902462fe'
silent! let g:plugs['vim-commentary'].commit = 'c4b8f52cbb7142ec239494e5a2c4a512f92c4d07'
silent! let g:plugs['vim-diminactive'].commit = '6f2e14e6ff6a038285937c378ec3685e6ff7ee36'
silent! let g:plugs['vim-eunuch'].commit = '8fb3904be27b6b60d086f87c2570085902414069'
silent! let g:plugs['vim-jdaddy'].commit = '23b67752cb869dd9c8f3109173b69aa96a1f3acf'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-vsnip'].commit = '02a8e79295c9733434aab4e0e2b8c4b7cea9f3a9'
silent! let g:plugs['xwiki.vim'].commit = '8551414062245924c870bd4049c166bab155f9f5'

" Uncomment to update
" PlugUpdate!

