" Generated by vim-plug
" Thu  3 Jul 15:51:47 2025
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['applescript.vim'].commit = '00840b4059c7884120913907f4778092edb006f7'
silent! let g:plugs['cmp-buffer'].commit = 'b74fab3656eea9de20a9b8116afa3cfc4ec09657'
silent! let g:plugs['cmp-cmdline'].commit = 'd126061b624e0af6c3a556428712dd4d4194ec6d'
silent! let g:plugs['cmp-nvim-lsp'].commit = 'a8912b88ce488f411177fc8aed358b04dc246d7b'
silent! let g:plugs['cmp-path'].commit = 'e52e640b7befd8113b3350f46e8cfcfe98fcf730'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['fzf'].commit = 'c4a9ccd6afc3698a57a6b938ebba6d85238033e2'
silent! let g:plugs['fzf.vim'].commit = '3725f364ccd25b85a91970720ba9bc2931861910'
silent! let g:plugs['indent-blankline.nvim'].commit = '005b56001b2cb30bfa61b7986bc50657816ba4ba'
silent! let g:plugs['mason-lspconfig.nvim'].commit = '73e0143385d8a2185944b42ed44d728b94ee19a3'
silent! let g:plugs['mason-tool-installer.nvim'].commit = '517ef5994ef9d6b738322664d5fdd948f0fdeb46'
silent! let g:plugs['mason.nvim'].commit = '8024d64e1330b86044fed4c8494ef3dcd483a67c'
silent! let g:plugs['neoformat'].commit = '9d2e28993e06e86b88c364b6176612b917468f3e'
silent! let g:plugs['nvim-cmp'].commit = 'b5311ab3ed9c846b585c0c15b7559be131ec4be9'
silent! let g:plugs['nvim-lspconfig'].commit = '1ddc1a2e692b120cda6d33c890461e49cb85d6bf'
silent! let g:plugs['nvim-tree.lua'].commit = 'b0b49552c9462900a882fe772993b01d780445fe'
" Leaving uncommented since we want latest updates
" silent! let g:plugs['nvim-treesitter'].commit = '42fc28ba918343ebfd5565147a42a26580579482'
silent! let g:plugs['nvim-web-devicons'].commit = '19d6211c78169e78bab372b585b6fb17ad974e82'
silent! let g:plugs['papercolor-theme'].commit = '0cfe64ffb24c21a6101b5f994ca342a74c977aef'
silent! let g:plugs['vim-argumentative'].commit = '63a5f7deb675c38126de626f4c00e000902462fe'
silent! let g:plugs['vim-commentary'].commit = '64a654ef4a20db1727938338310209b6a63f60c9'
silent! let g:plugs['vim-diminactive'].commit = '6f2e14e6ff6a038285937c378ec3685e6ff7ee36'
silent! let g:plugs['vim-eunuch'].commit = 'e86bb794a1c10a2edac130feb0ea590a00d03f1e'
silent! let g:plugs['vim-gitgutter'].commit = '85ca3a087204e3a32cb2faa5d9d0451524e08720'
silent! let g:plugs['vim-jdaddy'].commit = '23b67752cb869dd9c8f3109173b69aa96a1f3acf'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-vsnip'].commit = '0a4b8419e44f47c57eec4c90df17567ad4b1b36e'
silent! let g:plugs['xwiki.vim'].commit = '8551414062245924c870bd4049c166bab155f9f5'

" Uncomment to update
" PlugUpdate!
