#!/usr/bin/env bash
#
# Run all dotfiles installers.
# Adapted from https://github.com/holman/dotfiles/blob/master/script/install

set -e -x

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

